services:
  - type: web
    name: linkshrinker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: data
      mountPath: "/data"
      sizeGB: 1